### ISSUE TITLE
.d.ts missing in latest npm

### ISSUE THREAD

**Issue by steven-dawkins** [7eggs/node-toggl-api#14]
it looks like the index.d.ts file is missing in the latest npm package (1.0.1)

there is a reference to it in the package.json 
```json
"typings": "index.d.ts"
```

however the file itself is missing from the npm

**Comment by estliberitas** [comment]
Hey @steven-dawkins ! As you can see, I'm not maintaining this project for a long time already. So if anyone wants, I can give it away, so you can continue on the development (but maybe there are better clients for Toggl API).

**Comment by steven-dawkins** [comment]
Hi @estliberitas,

Thanks for the replay

I actually meant to open this issue for toggle-api instead of toggl-api

Your project actually looks a lot better!
