### ISSUE TITLE
Support Promises

### ISSUE THREAD

**Issue by dguo** [7eggs/node-toggl-api#16]
Hi, is there any interest in adding support for Promises? One technique is to check if a callback is provided, and if not, return a Promise. This method should maintain backwards compatibility.

**Comment by Yudikubota** [comment]
@estliberitas ?

**Comment by rzfzr** [comment]
Your [suggestion worked ](https://github.com/rzfzr/node-toggl-api/commit/c0b7f22cd588a2a617ddce028d414b01878f53ed)quite well.
This will be merged and published by me with the v9 migration, which is more urgent.
I didn't mean to start implementing this till v9 were done, but having this will avoid callback hell during testing all the endpoints.
